=== pars-linux/uludag/trunk/web/site/style/uludagbook.dtd
<!-- 
  Uludağ XML Dökümanları için DTD (Document Template Definition)
  
  Barış Metin <baris@uludag.org.tr>
-->

<!--
  Elementleri bu şekilde sınıflandırmak düzgün bir sıra düzeni
  (hiyerarşi) yaratıyor. Gentoo GuideXML'de de kullanılmış, 
  güzel de olmuş :). Sınıflar için aynı isimleri kullanacağım.
-->
<!ENTITY % style.class "em|underline|strong">
<!ENTITY % link.class "link|email">
<!ENTITY % list.class "numberedlist|orderedlist|descriptivelist">
<!-- simdilik yalnizca para'nin icerisinde kullanilanlar (logic?)-->
<!ENTITY % logic.class "graphic|note|attention|program|command|reference|quote"> 
<!ENTITY % all.class "%style.class;|%link.class;|%list.class;|%logic.class;">


<!ELEMENT book (bookinfo, chapter+, footer?)>

<!-- bookinfo -->
<!ELEMENT bookinfo (title, author+, pubdate, revhistory, abstract)>
<!ELEMENT title (#PCDATA)>
<!-- author -->
<!ELEMENT author (firstname, lastname, address?)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT address (email+, web*)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!-- author -->
<!ELEMENT pubdate (#PCDATA)>
<!-- revhistory -->
<!ELEMENT revhistory (revision+)>
<!ELEMENT revision (revnumber, date)>
<!ELEMENT revnumber (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!-- revhistory -->
<!ELEMENT abstract (para+)>
<!-- bookinfo -->


<!ELEMENT chapter (chapterinfo?, sect1+, footer?)>
<!ELEMENT chapterinfo (title, abstract)>
<!ELEMENT sect1 (title?, para+, sect2*, footer?)>
<!ELEMENT sect2 (title?, para+, sect3*, footer?)>
<!ELEMENT sect3 (title?, para+, footer?)>
<!ELEMENT footer (para)>

<!ELEMENT para (#PCDATA|%all.class;)*>

<!ELEMENT graphic EMPTY>
<!ELEMENT note (#PCDATA)>
<!ELEMENT attention (#PCDATA)>
<!ELEMENT program (#PCDATA)>
<!ELEMENT command (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT reference (#PCDATA)*>
<!ELEMENT quote (#PCDATA)*>

<!-- style.class -->
<!ELEMENT em (#PCDATA)*>
<!ELEMENT underline (#PCDATA)*>
<!ELEMENT strong (#PCDATA)*>

<!-- list.class -->
<!ELEMENT numberedlist (listitem+)>
<!ELEMENT orderedlist (listitem+)>
<!ELEMENT descriptivelist (listitem+)>
<!ELEMENT listitem (#PCDATA|%all.class;)*>


<!-- Attribute'lar -->
<!ATTLIST book
          version NMTOKEN #REQUIRED
	  lang (tr | en) #IMPLIED
	  id CDATA #IMPLIED
	  type (webpage | guide) #REQUIRED>

<!ATTLIST author
          author_id NMTOKEN #REQUIRED>

<!ATTLIST revision
          author_id NMTOKEN #REQUIRED>

<!ATTLIST chapter
	  id CDATA #IMPLIED>
<!ATTLIST sect1
	  id CDATA #IMPLIED>
<!ATTLIST sect2
	  id CDATA #IMPLIED>
<!ATTLIST sect3
	  id CDATA #IMPLIED>

<!ATTLIST graphic 
          source CDATA #REQUIRED
	  align (left | right | top | bottom) #IMPLIED>

<!ATTLIST link
          thispage CDATA #IMPLIED
	  url CDATA #IMPLIED>


<!NOTATION jpeg SYSTEM "image/jpeg">
<!NOTATION png SYSTEM "image/png">

=== pars-linux/uludag/web/site/en/projects/index.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE book SYSTEM "http://www.uludag.org.tr/style/uludagbook.dtd"
[
  <!ENTITY projectname "Uludağ">
]>


<book version="0.1" lang="tr" type="webpage">

  <bookinfo>
    <title>Projects</title>

    <author author_id="1">
      <firstname>Erkan</firstname>
      <lastname>Tekman</lastname>
      <address>
        <email>tekman@uludag.org.tr</email>
      </address>
    </author>
    <author author_id="2">
      <firstname>Barış</firstname>
      <lastname>Metin</lastname>
      <address>
        <email>baris@uludag.org.tr</email>
	<web>http://www.metin.org</web>
      </address>
    </author>

    <pubdate>2004-01-09</pubdate>
    <revhistory>
      <revision author_id="1">
        <revnumber>1.0</revnumber>
	<date>2004-01-09</date>
      </revision>
    </revhistory>

    <abstract>
      <para>
      We think it is essential to define sub-projects within Uludag to exploit parallel development and concurrent engineering methodologies. We prefer to do this by dividing Uludag into three layers.
      </para>
    </abstract>
  </bookinfo>


  <chapter>
    <sect1>
      <title>Core Layer</title>
      <para>
	This is the software packages and their connection to the system, which is <em>sine qua non</em> of Uludag, or any distribution.

        <orderedlist>
          <listitem>Packages Projects: Adapting the software packaging and preparing them for distribution.</listitem>
          <listitem>Package Management System Project: The configuration tool that handles the installation and management of application packages.</listitem>
          <listitem>Configuration Tools Project: The framework and the tools that takes care of configuration of the operating system and important applications.</listitem>
          <listitem>Installer Project: The software that installs the operating system onto a brand new or in use system.</listitem>
	</orderedlist>
      </para>
    </sect1>

    <sect1>
      <title>Presentation Layer</title>
      <para>
        The components that Uludag use to interface with the user.

        <orderedlist>
          <listitem>Turkish Project: Translating the operating system and the applications to Turkish, and guaranteeing that the Turkish characters and fonts work flawlessly.</listitem>
          <listitem>Graphics &amp; Media Project: Designing all visual and audio components of the desktop and the documents.</listitem>
          <listitem>Human-Computer Interaction Project: Developing all Uludag projects through a human-centric design approach and obeying the usability criteria.</listitem>
	</orderedlist>
      </para>
    </sect1>

    <sect1>
      <title>Auxiliary Layer</title>
      <para>
	The components which are not necessary <em>per se</em>, nevertheless of utmost importance for sustainability of Uludag.

        <orderedlist>
          <listitem>Quality Assurance Project: Defining, documenting and monitoring all the production processes of Uludag.</listitem>
          <listitem>Contributor Relations Project: Managing the relations with the developers who are volunteer to contribute to Uludag project.</listitem>
          <listitem>Developer System Project: Designing, deploying and managing the infrastructure that will be employed by all Uludag projects.</listitem>
	</orderedlist>
      </para>
    </sect1>
   </chapter>
</book>

=== pars-linux/uludag/web/site/tr/projeler/belgeler/index.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE book SYSTEM "http://www.uludag.org.tr/style/uludagbook.dtd"
[
]>

<book version="0.1" lang="tr" type="webpage">

  <bookinfo>
    <title>Belgeler</title>

    <author author_id="1">
      <firstname>Erkan</firstname>
      <lastname>Tekman</lastname>
      <address>
        <email>tekman@uludag.org.tr</email>
      </address>
    </author>
    <author author_id="1">
      <firstname>Barış</firstname>
      <lastname>Metin</lastname>
      <address>
	<email>baris@uludag.org.tr</email>
        <web>http://www.metin.org</web>
      </address>
    </author>

    <pubdate>2004-01-10</pubdate>
    <revhistory>
      <revision author_id="1">
        <revnumber>1.0</revnumber>
	<date>2004-01-10</date>
      </revision>
    </revhistory>

    <abstract>
      <para>
        Ulusal Dağıtım kapsamında oluşturulacak her tür (basılı, elektronik, çokluortam, vb.) belgenin hazırlanması Belgeler projesinin sorumluluğundadır. Belgelerde tutarlı bir üslup ve doku kullanılması en temel gereklerden biridir.
     </para>
   </abstract>
  </bookinfo>

  <chapter>
    <sect1>
      <para>
        Ulusal Dağıtım Belgeler Projesi kapsamında:
	<numberedlist>
	  <listitem>Kullanıcı ve geliştiricilere yönelik tüm belgeler belirlenecek ve sınıflandırılacak,</listitem>
	  <listitem>Bu belgelerin hazırlanma işi yürütülecek, yaptırılacak ve eşgüdümü sağlanacak,</listitem>
	  <listitem>Ulusal Dağıtım iç, dış ve geliştirici web sitelerinin enformasyon mimarisi ve içerik yönetimi yapılacak,</listitem>
	  <listitem>Belgeler sisteminin enformasyon mimarisi ve içerik yönetimi yapılacak,</listitem>
	  <listitem>Diğer projelerde oluşturulacak kılavuzların hazırlanmasında rol alacak,</listitem>
	  <listitem>Katkıcılardan gelen belgelerin kabul testleri yürütülecek, bu testler için süreç tanımı yapılacak ve kılavuz hazırlanacak.</listitem>
	</numberedlist>
      Proje iletişim: Zerrin Çakmakkaya, <email>zerrin@uludag.org.tr</email>
      </para>
    </sect1>
  </chapter>

</book>

=== pars-linux/uludag/web/site/tr/projeler/index.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE book SYSTEM "http://www.uludag.org.tr/style/uludagbook.dtd"
[
  <!ENTITY projectname "Ulusal Dağıtım">
]>


<book version="0.1" lang="tr" type="webpage">

  <bookinfo>
    <title>Projeler</title>

    <author author_id="1">
      <firstname>Erkan</firstname>
      <lastname>Tekman</lastname>
      <address>
        <email>tekman@uludag.org.tr</email>
      </address>
    </author>
    <author author_id="2">
      <firstname>Barış</firstname>
      <lastname>Metin</lastname>
      <address>
        <email>baris@uludag.org.tr</email>
	<web>http://www.metin.org</web>
      </address>
    </author>

    <pubdate>2004-01-09</pubdate>
    <revhistory>
      <revision author_id="1">
        <revnumber>1.0</revnumber>
	<date>2004-01-09</date>
      </revision>
    </revhistory>

    <abstract>
      <para>
      Ulusal Dağıtım'da paralel geliştirme ve eşzamanlı mühendislik yöntemlerini kullanabilmek için alt projeler tanımlananın yerinde olduğunu düşünüyoruz. Bu tanımlamaları da Ulusal Dağıtım'ı üç kavramsal katmana bölerek yürütmeyi uygun bulduk.
      </para>
    </abstract>
  </bookinfo>


  <chapter>
    <sect1>
      <title>Çekirdek Katmanı</title>
      <para>
        Ulusal Dağıtım'ın olmazsa olmazı yazılım paketleri ve bu paketlerin sistemle bağlantısını sağlayan temel bileşenler.

        <orderedlist>
          <listitem><link url="/projeler/paketler/">Paketler Projesi</link>: Uygulama paketlerini uyarlama ve dağıtıma hazırlama işi.</listitem>
          <listitem><link url="/projeler/pisi/">Paket Yönetim Sistemi Projesi</link>: Uygulama paketlerinin kurulumu ve yönetimini düzenleyen yapılandırma aracı.</listitem>
          <listitem><link url="/projeler/comar/">Yapılandırma Araçları Projesi</link>: İşletim sisteminin ve önemli uygulamaların yapılandırmalarını düzenleyen çerçeve ve araçlar.</listitem>
          <listitem><link url="/projeler/yali/">Kurulum Projesi</link>: İşletim sisteminin boş ya da kullanımdaki bir sisteme yüklenmesini sağlayan yazılım.</listitem>
	</orderedlist>
      </para>
    </sect1>
    
    <sect1>
      <title>Gösterim Katmanı</title>
      <para>
        Ulusal Dağıtım'ın kullanıcı ile arayüzünde kullandığı bileşenler.

        <orderedlist>
          <listitem><link url="/projeler/turkce/">Türkçe Projesi</link>: İşletim sistemi ve uygulamaların çevirilerinin yapılması ve Türkçe karakterler ve yazıtipleri ile uyumunun sağlanması işi.</listitem>
          <listitem><link url="/projeler/grafik/">Grafik &amp; Medya Projesi</link>: Masaüstü ve belgelerin görsel ve işitsel unsurlarının tasarlanması işi.</listitem>
          <listitem><link url="/projeler/ibe/">İnsan-Bilgisayar Etkileşimi Projesi</link>: Tüm Ulusal Dağıtım projelerinin insan merkezli tasarım yaklaşımı ile ve kullanışlılık ilkelerine uyarak şekillendirilmesi işi.</listitem>
	</orderedlist>
      </para>
    </sect1>
	   
    <sect1>
      <title>Yardımcı Katman</title>
      <para>
Ulusal Dağıtım'ın sürdürülebilirliğini sağlayacak olan, ancak dağıtımın kendisi için doğrudan gerekli olmayan bileşenler.

        <orderedlist>
          <listitem><link url="/projeler/kalite/">Kalite Güvence Projesi</link>: Ulusal Dağıtım'ın tüm üretim süreçlerinin tanımlanması, belgelenmesi ve izlenmesi işi.</listitem>
          <listitem><link url="/projeler/iliskiler/">Katkıcı İlişkileri Projesi</link>: Ulusal Dağıtım projesine katkıda bulunmak isteyen kişilerle ilişkilerin yürütülmesi.</listitem>
          <listitem><link url="/projeler/gelistirici/">Geliştirici Sistemi Projesi</link>: Tüm Ulusal Dağıtım projelerinin yürütüleceği altyapı ve hizmetlerin tasarlanması, kurulması ve sunulması işi.</listitem>
	</orderedlist>
      </para>
    </sect1>
   </chapter>
</book>

=== pars-linux/uludag/web/site/tr/projeler/grafik/index.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE book SYSTEM "http://www.uludag.org.tr/style/uludagbook.dtd"
[
]>

<book version="0.1" lang="tr" type="webpage">

  <bookinfo>
    <title>Grafik &amp; Medya</title>

    <author author_id="1">
      <firstname>Erkan</firstname>
      <lastname>Tekman</lastname>
      <address>
        <email>tekman@uludag.org.tr</email>
      </address>
    </author>
    <author author_id="1">
      <firstname>Barış</firstname>
      <lastname>Metin</lastname>
      <address>
	<email>baris@uludag.org.tr</email>
        <web>http://www.metin.org</web>
      </address>
    </author>

    <pubdate>2004-01-10</pubdate>
    <revhistory>
      <revision author_id="1">
        <revnumber>1.0</revnumber>
	<date>2004-01-10</date>
      </revision>
    </revhistory>

    <abstract>
      <para>
        Ulusal Dağıtım projesinde kullanılacak tüm görsel ve işitsel malzeme bu proje kapsamında hazırlanacak ya da hazırlatılacaktır.
      </para>
    </abstract>
  </bookinfo>

  <chapter>
    <sect1>
      <para>
        Ulusal Dağıtım Grafik &amp; Medya Projesi kapsamında:
	<numberedlist>
	  <listitem>Seçili masaüstü için arkaplan, ikonlar, imleçler, görsel ve işitsel uyarılar tasarlanacak,</listitem>
	  <listitem>Seçili pencere yöneticisi için pencere unsurları tasarlanacak,</listitem>
	  <listitem>Seçili masaüstü ve pencere sistemi için font ve renk grupları belirlenecek, gerekirse font tasarımı yapılacak,</listitem>
	  <listitem>Yukarıdaki işlemler mümkünse birden fazla tema için yinelenecek,</listitem>
	  <listitem>Yerelde üretilen (örneğin Yapılandırma Araçları projesinin ürünleri) uygulamalar için görsel ve işitsel öğeler yukarıdaki temalara uygun olarak tasarlanacak,</listitem>
	  <listitem>Gerekli durumlarda kaynağından alınan uygulamalar için görsel ve işitsel öğeler yine yukarıdaki temalara uygun olarak tasarlanacak,</listitem>
	  <listitem>Kurulumun grafik ve medya işleri yapılacak,</listitem>
	  <listitem>Belgelerin grafik ve medya işleri yapılacak,</listitem>
	  <listitem>Dağıtım için görsel öğeler kuralları belirlenecek ve kılavuzu hazırlanacak,</listitem>
	  <listitem>Katkıcılardan gelen görsel ve işitsel öğelerin kabul testleri yürütülecek, bu testler için süreç tanımı yapılacak ve kılavuz hazırlanacak,</listitem>
	  <listitem>Gerekirse halkla ilişkiler, tanıtım ve pazarlama için görsel ve işitsel öğeler tasarlanacak ya da tasarlatılacak.</listitem>
	</numberedlist>
        Proje iletişim: Ayşe Genç, <email>ayse@uludag.org.tr</email>
      </para>
    </sect1>
  </chapter>

</book>

=== pars-linux/uludag/eski_web/site/en/aboutus/whower.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE book SYSTEM "http://www.uludag.org.tr/style/uludagbook.dtd"
[
]>

<book version="0.1" lang="tr" type="webpage">

  <bookinfo>
    <title>Who We Are</title>

    <author author_id="1">
      <firstname>Erkan</firstname>
      <lastname>Tekman</lastname>
      <address>
        <email>tekman@uludag.org.tr</email>
      </address>
    </author>
    <author author_id="1">
      <firstname>Barış</firstname>
      <lastname>Metin</lastname>
      <address>
	<email>baris@uludag.org.tr</email>
        <web>http://www.metin.org</web>
      </address>
    </author>

    <pubdate>2004-01-10</pubdate>
    <revhistory>
      <revision author_id="1">
        <revnumber>1.0</revnumber>
	<date>2004-01-10</date>
      </revision>
    </revhistory>

    <abstract>
      <para>
        Uludag developers and their contact info are listed below.
      </para>
    </abstract>
  </bookinfo>

  <chapter>
    <sect1>
    <para>
      <orderedlist>

      <listitem>
	A. Murat Eren
	<descriptivelist>
         <listitem>E-Mail: <email>meren@uludag.org.tr</email></listitem>
	 <listitem>Web: <link url="http://cekirdek.uludag.org.tr/~meren/">http://cekirdek.uludag.org.tr/~meren/</link></listitem>
	</descriptivelist>
      </listitem>				      

      <listitem>
	Alp Öztarhan
	<descriptivelist>
	  <listitem>E-Mail: <email>alp@uludag.org.tr</email></listitem>
	</descriptivelist>
      </listitem>

      <listitem>
	Ayşe Genç
	<descriptivelist>
	  <listitem>E-Mail: <email>ayse@uludag.org.tr</email></listitem>
	</descriptivelist>
      </listitem>

      <listitem>
	Barış Metin 
	<descriptivelist>
	  <listitem>E-Mail: <email>baris@uludag.org.tr</email></listitem>
	  <listitem>Web: <link url="http://cekirdek.uludag.org.tr/~baris/">http://cekirdek.uludag.org.tr/~baris/</link></listitem>
	  <listitem>Web: <link url="http://www.metin.org">http://www.metin.org</link></listitem>
	</descriptivelist>
      </listitem>

      <listitem>
        Erkan Tekman
	<descriptivelist>
	  <listitem>E-Mail: <email>tekman@uludag.org.tr</email></listitem>
	  <listitem>Web: <link url="http://cekirdek.uludag.org.tr/~tekman/">http://cekirdek.uludag.org.tr/~tekman/</link></listitem>
	</descriptivelist>
      </listitem>

      <listitem>
        Serdar Köylü
	<descriptivelist>
	  <listitem>E-Mail: <email>serdar@uludag.org.tr</email></listitem>
	</descriptivelist>
      </listitem>

      <listitem>
        Zerrin Çakmakkaya
	<descriptivelist>
	  <listitem>E-Mail: <email>zerrin@uludag.org.tr</email></listitem>
	</descriptivelist>
      </listitem>
      </orderedlist>
    </para>
    </sect1>
  </chapter>

</book>

=== pars-linux/uludag/web/site/en/projects/yali/index.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE book SYSTEM "http://www.uludag.org.tr/style/uludagbook.dtd"
[
]>

<book version="0.1" lang="tr" type="webpage">

  <bookinfo>
    <title>Installer</title>

    <author author_id="1">
      <firstname>Erkan</firstname>
      <lastname>Tekman</lastname>
      <address>
        <email>tekman@uludag.org.tr</email>
      </address>
    </author>
    <author author_id="1">
      <firstname>Barış</firstname>
      <lastname>Metin</lastname>
      <address>
	<email>baris@uludag.org.tr</email>
        <web>http://www.metin.org</web>
      </address>
    </author>

    <pubdate>2004-01-10</pubdate>
    <revhistory>
      <revision author_id="1">
        <revnumber>1.0</revnumber>
	<date>2004-01-10</date>
      </revision>
    </revhistory>

    <abstract>
      <para>
	The installer software is the system that installs the operating system and the user's choice application from the installation media (CD, network, internet, etc.) quickly and problem-free. It is expected to end up with a functional system which requires no further configuration when the installer application finishes, which is generally used only once.
      </para>
    </abstract>
  </bookinfo>

  <chapter>
    <sect1>
      <para>
        Within the scope of Uludag Installer Project:
	<numberedlist>
	  <listitem>An installation scenario will be written,</listitem>
	  <listitem>This scenario will be put through user tests and usability aspects will be examined,</listitem>
	  <listitem>A user interface will be designed for the finalized scenario,</listitem>
	  <listitem>The requirements for the software to run underneath this interface/scenario will be determined,</listitem>
	  <listitem>The interface/scenario will be iterated until technical feasibility is reached,</listitem>
	  <listitem>The graphics and media tasks for the installer will be outsourced,</listitem>
	  <listitem>The installer software will be designed and coded,</listitem>
	  <listitem>The final acceptance tests will be carried out on the real system.</listitem>
	</numberedlist>
        Project contact: Barış Metin, <email>baris@uludag.org.tr</email>
      </para>
    </sect1>
  </chapter>

</book>

=== pars-linux/uludag/trunk/eski_web/site/en/aboutus/history.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE book SYSTEM "http://www.uludag.org.tr/style/uludagbook.dtd"
[
]>

<book version="0.1" lang="tr" type="webpage">

  <bookinfo>
    <title>History of Uludag</title>

    <author author_id="1">
      <firstname>Erkan</firstname>
      <lastname>Tekman</lastname>
      <address>
        <email>tekman@uludag.org.tr</email>
      </address>
    </author>
    <author author_id="2">
      <firstname>Barış</firstname>
      <lastname>Metin</lastname>
      <address>
        <email>baris@uludag.org.tr</email>
	<web>http://www.metin.org</web>
      </address>
    </author>

    <pubdate>2004-01-10</pubdate>
    <revhistory>
      <revision author_id="1">
        <revnumber>1.0</revnumber>
	<date>2004-01-10</date>
      </revision>
    </revhistory>

    <abstract>
      <para>
        The preparation for the Turkish Linux Distribution (Uluda) project dates back more than one year. We are aware that a sound preparation is as important as good planning and fast execution for the success of the project. Thus, we preferred not the start Uludag project till the project foundation matured enough.
      </para>
    </abstract>
  </bookinfo>

  <chapter>
    <sect1>
      <title>Concept</title>
      <para>
	Through most of 2003 we have carried extensive research on the necessity of a national operating system distribution, similar initiatives around the globe, the current position and trends of local software industry. Information technology applications and software of critical national importance have been reviewed. National human resources, capabilities of the local software industry and competitive advantages have been analyzed. This research paved way to the decision to develop a national Linux distribution, in Summer 2003.
      </para>
    </sect1>

    <sect1>
      <title>Decision</title>
      <para>
	Following the decision to develop a national Linux distribution, a rather concrete planning phase started. Present operating systems and distributions, foremost Linux distributions, have been examined. SWOT (Strength-Weakness-Opportunity-Threat) analyses for these have been carried out. Open source software methodology and the underlying philosophy have been recited thoroughly. New business models for software industry, especially in the open source context, have been studied since we aim to found a sustainable organization, in addition to developing a distribution. In Fall 2003, we have reached the conclusion that a Linux-based, open source, distribution licensed through GPL to the extent possible has to be developed.
      </para>
    </sect1>

    <sect1>
      <title>Foundation</title>
      <para>
	After deciding on a Linux-based operating system distribution detail planning has started. Processes for developing a Linux distribution have been identified and possible human resource requirements have been determined. Open source software repository has been searched and sources that may be reused for the distribution have been pointed out. Different distributions have been studied and compared in terms of their target groups, development methodologies and business models. Alternatives have been established. By Fall 2003 the basic components of the project plan for the distribution have been completed.
      </para>
    </sect1>

    <sect1>
      <title>Team</title>
      <para>
	Since the project plan emerged to a certain degree, it was time to focus on more technical aspects. The core of the team to design the architecture and develop the national distribution has been selected and employed. Special emphasis is placed on the history of Linux in Turkey, existing and planned distributions, open source and Linux community and initiatives, and utmost importance is given to make use of the present know-how and experience. By the end of 2003 the core team has been established and the execution of the project has started.
      </para>
    </sect1>

    <sect1>
      <title>Plan</title>
      <para>
	Work on detail plan for Uludag project has started, following the identification of the basic components of a Linux distribution and the relevant processes. For the sake of flexibility and manageability the Uludag project has been divided into (sub) projects, and the scope for these projects has been determined. The infrastructure for developing the distribution has been itemized and a successive plan for deploying this infrastructure has been initiated. The basic components of Uludag, that will be developed mainly in-house, have been identified and requirement analyses for these have been carried out. By early 2004 the Plan phase has been completed and the Design phase has started.
      </para>
    </sect1>

  </chapter>

</book>

=== pars-linux/uludag/trunk/eski_web/site/tr/hakkimizda/tarihce.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE book SYSTEM "http://www.uludag.org.tr/style/uludagbook.dtd"
[
]>

<book version="0.1" lang="tr" type="webpage">

  <bookinfo>
    <title>Ulusal Dağıtım Tarihçesi</title>

    <author author_id="1">
      <firstname>Erkan</firstname>
      <lastname>Tekman</lastname>
      <address>
        <email>tekman@uludag.org.tr</email>
      </address>
    </author>
    <author author_id="2">
      <firstname>Barış</firstname>
      <lastname>Metin</lastname>
      <address>
        <email>baris@uludag.org.tr</email>
	<web>http://www.metin.org</web>
      </address>
    </author>

    <pubdate>2004-01-10</pubdate>
    <revhistory>
      <revision author_id="1">
        <revnumber>1.0</revnumber>
	<date>2004-01-10</date>
      </revision>
    </revhistory>

    <abstract>
      <para>
        Ulusal Dağıtım projesi bir yılı aşan bir süredir hazırlıkları sürdürülmekte olan bir girişimdir. Projenin başarısında sağlam bir hazırlık döneminin en azından iyi planlama ve hızlı uygulama kadar önemi olduğuna inanıyoruz. Bu nedenle proje temelini olgunlaştırmadan Ulusal Dağıtım'ı oluşturma işine başlamamayı tercih ettik.
      </para>
    </abstract>
  </bookinfo>

  <chapter>
    <sect1>
      <title>Kavram</title>
      <para>
        2003 yılının önemli bir bölümünde ulusal bir dağıtımın gerekliliği, dünyada benzer uygulamalar, yazılım endüstrisinin mevcut durumu ve eğilimleri konularında geniş ve çok yönlü araştırmalar yürütüldü. Ulusal bağımsızlık ve güvenlik bağlamında kritik öneme sahip bilgi teknolojisi uygulamaları ve yazılımlar gözden geçirildi. Ülkenin bilgi teknolojisi alanındaki insan kaynağı, yerel yazılım sanayinin yetenekleri ve rekabet unsurları incelendi. Tüm bulgular ışığında, 2003 yılı Yazı'nda, bir ulusal işletim sistemi dağıtımı oluşturmanın yerinde bir karar olduğu sonucuna varıldı. 
      </para>
    </sect1>

    <sect1>
      <title>Karar</title>
      <para>
        Bir ulusal işletim sistemi dağıtımı oluşturmaya karar verdikten sonra daha somut düzeyde planlama işine girildi. Mevcut işletim sistemleri, başta Linux olmak üzere dağıtımlar incelendi, ZGFT (Zayıf-Güçlü-Fırsat-Tehdit) çözümlemeleri yapıldı, açık kaynak yazılım metodolojisi ve felsefesi ayrıntılı olarak çalışıldı. Hedef, bir dağıtım oluşturmanın ötesinde, bu dağıtımı sürekli kılabilecek organizasyonel yapıyı da kurmak olduğundan yazılım endüstrisinde, özellikle açık kaynak çerçevesinde, kullanılabilecek iş modelleri irdelendi. Bu incelemeler sonrasında, 2003 yılı Güzü'nde, Linux temelli, açık kaynak, olabildiğince GPL lisanslama yöntemini kullanan bir işletim sistemi dağıtımı oluşturulmasına karar verildi.
      </para>
    </sect1>
    
    <sect1>
      <title>Temel</title>
      <para>
        Linux temelli bir işletim sistemi dağıtımı oluşturulmasına karar verilmesi ile ayrıntı planlama sürecine girildi. Bir Linux dağıtımı oluşturma işi süreçleri tanımlandı ve olası işgücü gereksinimi belirlendi. Açık kaynak yazılım dağarcığı incelendi ve dağıtımı oluşturma aşamasında yararlanılabilecek kaynaklar belirlendi. Farklı dağıtımlar, hedef kitleleri, geliştirilme yöntemleri ve iş modelleri açısından karşılaştırıldı ve pazar açısından uygulanabilecek seçenekler oluşturuldu. Bu çalışmalar sonuçlandığında, 2003 yılı Güzü'nde, ulusal dağıtım işinin uygulama planı temel unsurları ile ortaya çıkarıldı.
      </para>
    </sect1>

    <sect1>
      <title>Ekip</title>
      <para>
        Uygulama planının belirginleşmesi ile birlikte teknik işlere ağırlık verme zamanı geldi. Ulusal dağıtımı oluşturacak ekibin çekirdeğini oluşturacak, dağıtımın mimarisini hazırlayacak olan elemanların seçilmesi ve istihdamı yoluna gidildi. Bu aşamada Türkiye'nin Linux geçmişi, mevcut ve planlanan dağıtımlar, açık kaynak ve Linux camiası ve girişimleri de göz önüne alınarak var olan bilgi birikimi ve deneyimden en üst düzeyde yararlanmanın yoları arandı. Nihayet 2003 yılı sonunda çekirdek kadronun oluşturulması ile projenin uygulama safhası başlatıldı.
      </para>
    </sect1>

    <sect1>
      <title>Plan</title>
      <para>
        Bir Linux dağıtımının temel unsurlarının belirlenmesi ve dağıtım oluşturma süreçlerinin tanımlanması ile Ulusal Dağıtım projesinin ayrıntı planı hazırlanmasına geçildi. Esneklik ve yönetim kolaylığı açısından Ulusal Dağıtım (alt) projelere bölündü ve bu projelerin kapsamları belirlendi. Dağıtım oluşturma işi için gerekli altyapı planlandı ve bu altyapının aşamalı  olarak kurulmasına başlandı. Ulusal Dağıtım'ın yerelde geliştirilecek temel bileşenleri belirlendi ve bu bileşenler için gerekler çözümlemesi işi başlatıldı. 2004 yılı başı itibarıyla Plan aşaması tamamlanıp Tasarım aşamasına geçildi.
      </para>
    </sect1>

  </chapter>

</book>
