=== pars-linux/uludag/trunk/web/site/style/uludagbook.dtd
<!-- 
  Uludağ XML Dökümanları için DTD (Document Template Definition)
  
  Barış Metin <baris@uludag.org.tr>
-->

<!--
  Elementleri bu şekilde sınıflandırmak düzgün bir sıra düzeni
  (hiyerarşi) yaratıyor. Gentoo GuideXML'de de kullanılmış, 
  güzel de olmuş :). Sınıflar için aynı isimleri kullanacağım.
-->
<!ENTITY % style.class "em|underline|strong">
<!ENTITY % link.class "link|email">
<!ENTITY % list.class "numberedlist|orderedlist|descriptivelist">
<!-- simdilik yalnizca para'nin icerisinde kullanilanlar (logic?)-->
<!ENTITY % logic.class "graphic|note|attention|program|command|reference|quote"> 
<!ENTITY % all.class "%style.class;|%link.class;|%list.class;|%logic.class;">


<!ELEMENT book (bookinfo, chapter+, footer?)>

<!-- bookinfo -->
<!ELEMENT bookinfo (title, author+, pubdate, revhistory, abstract)>
<!ELEMENT title (#PCDATA)>
<!-- author -->
<!ELEMENT author (firstname, lastname, address?)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT address (email+, web*)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!-- author -->
<!ELEMENT pubdate (#PCDATA)>
<!-- revhistory -->
<!ELEMENT revhistory (revision+)>
<!ELEMENT revision (revnumber, date)>
<!ELEMENT revnumber (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!-- revhistory -->
<!ELEMENT abstract (para+)>
<!-- bookinfo -->


<!ELEMENT chapter (chapterinfo?, sect1+, footer?)>
<!ELEMENT chapterinfo (title, abstract)>
<!ELEMENT sect1 (title?, para+, sect2*, footer?)>
<!ELEMENT sect2 (title?, para+, sect3*, footer?)>
<!ELEMENT sect3 (title?, para+, footer?)>
<!ELEMENT footer (para)>

<!ELEMENT para (#PCDATA|%all.class;)*>

<!ELEMENT graphic EMPTY>
<!ELEMENT note (#PCDATA)>
<!ELEMENT attention (#PCDATA)>
<!ELEMENT program (#PCDATA)>
<!ELEMENT command (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT reference (#PCDATA)*>
<!ELEMENT quote (#PCDATA)*>

<!-- style.class -->
<!ELEMENT em (#PCDATA)*>
<!ELEMENT underline (#PCDATA)*>
<!ELEMENT strong (#PCDATA)*>

<!-- list.class -->
<!ELEMENT numberedlist (listitem+)>
<!ELEMENT orderedlist (listitem+)>
<!ELEMENT descriptivelist (listitem+)>
<!ELEMENT listitem (#PCDATA|%all.class;)*>


<!-- Attribute'lar -->
<!ATTLIST book
          version NMTOKEN #REQUIRED
	  lang (tr | en) #IMPLIED
	  id CDATA #IMPLIED
	  type (webpage | guide) #REQUIRED>

<!ATTLIST author
          author_id NMTOKEN #REQUIRED>

<!ATTLIST revision
          author_id NMTOKEN #REQUIRED>

<!ATTLIST chapter
	  id CDATA #IMPLIED>
<!ATTLIST sect1
	  id CDATA #IMPLIED>
<!ATTLIST sect2
	  id CDATA #IMPLIED>
<!ATTLIST sect3
	  id CDATA #IMPLIED>

<!ATTLIST graphic 
          source CDATA #REQUIRED
	  align (left | right | top | bottom) #IMPLIED>

<!ATTLIST link
          thispage CDATA #IMPLIED
	  url CDATA #IMPLIED>


<!NOTATION jpeg SYSTEM "image/jpeg">
<!NOTATION png SYSTEM "image/png">

=== pars-linux/uludag/eski_web/site/tr/svn/index.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE book SYSTEM "http://www.uludag.org.tr/style/uludagbook.dtd"
[
  <!ENTITY projectname "Ulusal Dağıtım">
]>


<book version="0.1" lang="tr" type="webpage">

  <bookinfo>
    <title>&projectname; Subversion Deposu</title>

    <author author_id="1">
      <firstname>Barış</firstname>
      <lastname>Metin</lastname>
      <address>
        <email>baris@uludag.org.tr</email>
	<web>http://www.metin.org</web>
      </address>
    </author>

    <pubdate>2004-04-27</pubdate>
    <revhistory>
      <revision author_id="1">
        <revnumber>1.0</revnumber>
	<date>2004-04-27</date>
      </revision>
    </revhistory>

    <abstract>
      <para>
        Projenin ürünlerinin sunulduğu Subversion sürüm kontrol sistemidir.
      </para>
    </abstract>
  </bookinfo>


  <chapter>
    <sect1>
      <title>&projectname; deposu</title>
      <para>
        &projectname; Subversion deposuna web üzerinden göz atmak için <link url="http://www.uludag.org.tr/uludag-xml/">http://www.uludag.org.tr/uludag-xml</link> adresini kullanabilirsiniz. Bağlantı web üzerinden gösterim için yapılandırılmıştır.
      </para>
      <para>
        Aslen, depoya ulaşmak için <link url="http://svn.uludag.org.tr/uludag/">http://svn.uludag.org.tr/uludag</link> adresi kullanılmalıdır.
      </para>
      <para>
        Kendi çalışma kopyanızı (working copy) oluşturup üzerinde çalışmak için;
        <command>svn co http://svn.uludag.org.tr/uludag</command>
        komutunu kullanabilirsiniz.
      </para>
      <para>
        Subversion hakkında bilgi almak için <link url="http://svnbook.red-bean.com/">http://svnbook.red-bean.com/</link> adresindeki Subversion kitabını kullanabilirsiniz.
      </para>
    </sect1>

    <sect1>
      <title>svn-commits e-posta listesi</title>
      <para>
        <link url="http://liste.uludag.org.tr/cgi-bin/mailman/listinfo/svn-commits">http://liste.uludag.org.tr/cgi-bin/mailman/listinfo/svn-commits</link> adresinden üye olabileceğiniz liste, Subversion deposundaki değişiklikleri anlık olarak e-posta adresinize gönderecektir.
      </para>
    </sect1>

  </chapter>
	   
</book>

=== pars-linux/uludag/trunk/eski_web/site/tr/projeler/kalite/index.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE book SYSTEM "http://www.uludag.org.tr/style/uludagbook.dtd"
[
]>

<book version="0.1" lang="tr" type="webpage">

  <bookinfo>
    <title>Kalite Güvence</title>

    <author author_id="1">
      <firstname>Erkan</firstname>
      <lastname>Tekman</lastname>
      <address>
        <email>tekman@uludag.org.tr</email>
      </address>
    </author>
    <author author_id="1">
      <firstname>Barış</firstname>
      <lastname>Metin</lastname>
      <address>
	<email>baris@uludag.org.tr</email>
        <web>http://www.metin.org</web>
      </address>
    </author>

    <pubdate>2004-01-10</pubdate>
    <revhistory>
      <revision author_id="1">
        <revnumber>1.0</revnumber>
	<date>2004-01-10</date>
      </revision>
    </revhistory>

    <abstract>
      <para>
        Ulusal Dağıtım sürümlerinin ve süreçlerinin kalitesi ve standartlara uygunluğunu sağlayacak, izleyecek ve yönetecek olan Kalite Güvence projesidir. Bu proje değer katmayan süreçler içerse de ürün ve üretim açısından merkezi öneme sahiptir.
      </para>
    </abstract>

  </bookinfo>

  <chapter>
    <sect1>
      <para>
        Ulusal Dağıtım Kalite Güvence Projesi kapsamında:
        <numberedlist>
	  <listitem>Tüm projelerde izlenecek süreçler belirlenecek, kriterleri tanımlanacak, tutarlılıkları sağlanacak ve belgelenecek,</listitem>
	  <listitem>Başarı ölçütleri belirlenecek, ölçme süreçleri oluşturulacak ve yürütülecek,</listitem>
	  <listitem>Dış standartlar izlenecek, iç standartlar oluşturulacak ve belgelenecek,</listitem>
	  <listitem>Ulusal Dağıtım iç, dış ve geliştirici web sitelerinin enformasyon mimarisi ve içerik yönetimi yapılacak, belgeler sisteminin enformasyon mimarisi ve içerik yönetimi yapılacak,</listitem>
	  <listitem>Tüm projelerde oluşturulacak belgelerin ve klavuzların kalite kıstasları ve standartlara uygunluğu izlenecek, bu belgelerin hazırlanma işi yaptırılacak ve eşgüdümü sağlanacak,</listitem>
	  <listitem>Tüm dış katkılar için kalite güvence kıstasları ve kuralları belirlenecek, kılavuzlar oluşturulacak.</listitem>
        </numberedlist>
        Proje iletişim: Zerrin Çakmakkaya, <email>zerrin@uludag.org.tr</email>
      </para>
    </sect1>
  </chapter>

</book>

=== pars-linux/uludag/eski_web/site/tr/projeler/pisi/index.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE book SYSTEM "http://www.uludag.org.tr/style/uludagbook.dtd"
[
]>

<book version="0.1" lang="tr" type="webpage">

  <bookinfo>
    <title>Paket Yönetim Sistemi</title>

    <author author_id="1">
      <firstname>Erkan</firstname>
      <lastname>Tekman</lastname>
      <address>
        <email>tekman@uludag.org.tr</email>
      </address>
    </author>
    <author author_id="1">
      <firstname>Barış</firstname>
      <lastname>Metin</lastname>
      <address>
	<email>baris@uludag.org.tr</email>
        <web>http://www.metin.org</web>
      </address>
    </author>

    <pubdate>2004-01-10</pubdate>
    <revhistory>
      <revision author_id="1">
        <revnumber>1.0</revnumber>
	<date>2004-01-10</date>
      </revision>
    </revhistory>

    <abstract>
      <para>
        Paket Yönetim Sistemi, paketlerin sisteme sorunsuz bir şekilde eklenip çıkarılmasını sağlayan uygulama/yapılandırma aracıdır. Paket Yönetim Sistemi, oluşturulması planlanan yönetim çerçevesinin (önemli) bir bileşenidir.
      </para>
    </abstract>
  </bookinfo>

  <chapter>
    <sect1>
      <para>
        Ulusal Dağıtım Paket Yönetim Sistemi Projesi kapsamında:
	<numberedlist>
	  <listitem>Paket Yönetim Sistemi için kullanıcı gerekleri belirlenecek,</listitem>
          <listitem>Bu gereklerle bağlantılı olarak paketlerin sağlaması gereken özellikler, paket metadata içerisinde yer alması gereken öğeler, paketlerin ayar ve yapılandırma gereksinimleri tespit edilecek,</listitem>
          <listitem>Paket oluşturucular ve katkıcıların Paket Yönetim Sistemi çerçevesine uygun paketler hazırlaması için kurallar belirlenecek ve geliştirici kılavuzu hazırlanacak,</listitem>
	  <listitem>Belirlenen kullanıcı gereklerine uygun olarak Paket Yönetim Sistemi tasarımı yapılacak,</listitem>
	  <listitem>Tasarım çerçevesinde Paket Yönetim Sistemi kodlaması yapılacak,</listitem>
	  <listitem>Referans sistemde testten geçirerek Paket Yönetim Sistemi için müşteri kabulü yapılacak.</listitem>
	</numberedlist>
	
	Proje iletişim: Alp Öztarhan, <email>alp@uludag.org.tr</email>
      </para>
    </sect1>
  </chapter>

</book>

=== pars-linux/uludag/web/site/tr/projeler/yali/index.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE book SYSTEM "http://www.uludag.org.tr/style/uludagbook.dtd"
[
]>

<book version="0.1" lang="tr" type="webpage">

  <bookinfo>
    <title>Kurulum</title>

    <author author_id="1">
      <firstname>Erkan</firstname>
      <lastname>Tekman</lastname>
      <address>
        <email>tekman@uludag.org.tr</email>
      </address>
    </author>
    <author author_id="1">
      <firstname>Barış</firstname>
      <lastname>Metin</lastname>
      <address>
	<email>baris@uludag.org.tr</email>
        <web>http://www.metin.org</web>
      </address>
    </author>

    <pubdate>2004-01-10</pubdate>
    <revhistory>
      <revision author_id="1">
        <revnumber>1.0</revnumber>
	<date>2004-01-10</date>
      </revision>
    </revhistory>

    <abstract>
      <para>
        Kurulum yazılımı, işletim sistemi ve kullanıcının seçeceği paketleri hızlı ve sorunsuz olarak kurulum medyasından (CD, ağ, İnternet, vb.) sisteme indiren ve yerleştiren sistemdir. Bir kez kullanılması beklenen kurulum yazılımının çalışması sona erdiğinde tercihen daha fazla yapılandırılması gerekmeyen işlevsel bir sistem oluşması beklenmektedir.
      </para>
    </abstract>
  </bookinfo>

  <chapter>
    <sect1>
      <para>
        Ulusal Dağıtım Kurulum Projesi kapsamında:
	<numberedlist>
	  <listitem>Kurulum senaryosu oluşturulacak,</listitem>
	  <listitem>Bu senaryo denekler üzerinde uygulanarak kullanışlılık açısından gözden geçirilecek,</listitem>
	  <listitem>Son haline getirilen senaryonun kullanıcı arayüzü oluşturulacak,</listitem>
	  <listitem>Bu senaryo/arayüz altında çalışacak yazılım için gerekler belirlenecek,</listitem>
	  <listitem>Teknik olabilirlik sağlanana kadar senaryo/arayüz üzerinde değişiklikler yapılacak,</listitem>
	  <listitem>Kurulumun grafik ve medya işleri yaptırılacak,</listitem>
	  <listitem>Kurulum yazılımı tasarlanacak ve kodlanacak,</listitem>
	  <listitem>Gerçek sistem üzerinde son testler yapılacak ve müşteri kabulü gerçekleştirilecek.</listitem>
	</numberedlist>
        Proje iletişim: Barış Metin, <email>baris@uludag.org.tr</email>
      </para>
    </sect1>
  </chapter>

</book>

=== pars-linux/uludag/trunk/eski_web/site/tr/projeler/ibe/index.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE book SYSTEM "http://www.uludag.org.tr/style/uludagbook.dtd"
[
]>

<book version="0.1" lang="tr" type="webpage">

  <bookinfo>
    <title>İnsan-Bilgisayar Etkileşimi</title>

    <author author_id="1">
      <firstname>Erkan</firstname>
      <lastname>Tekman</lastname>
      <address>
        <email>tekman@uludag.org.tr</email>
      </address>
    </author>
    <author author_id="1">
      <firstname>Barış</firstname>
      <lastname>Metin</lastname>
      <address>
	<email>baris@uludag.org.tr</email>
        <web>http://www.metin.org</web>
      </address>
    </author>

    <pubdate>2004-01-10</pubdate>
    <revhistory>
      <revision author_id="1">
        <revnumber>1.0</revnumber>
	<date>2004-01-10</date>
      </revision>
    </revhistory>

    <abstract>
      <para>
        Ulusal Dağıtım hedefleri arasında kolay kurulabilen ve kullanılabilen bir dağıtım oluşturmak yer aldığından en önemli projelerimizden birisi İnsan-Bilgisayar Etkileşimi projesi olacak.
      </para>
    </abstract>
  </bookinfo>

  <chapter>
    <sect1>
      <para>
	      Ulusal Dağıtım İnsan - Bilgisayar Etkileşimi Projesi kapsamında:
	      <numberedlist>
	        <listitem>Uygulama, sistem, vb. için kağıt maketler tasarlanacak ve hazırlatılacak,</listitem>
	        <listitem>Kullanışlılık testleri yapılacak/yaptırılacak, kullanışlılık raporları yazılacak/yazdırılacak,</listitem>
	        <listitem>Kurulum, Yapılandırma Araçları ve Grafik &amp; Medya projeleri başta olmak üzere tüm projelere kullanışlılık ve İBE desteği verilecek,</listitem>
	        <listitem>Dağıtım için kullanışlılık ve İBE kuralları belirlenecek ve kılavuzu hazırlanacak,</listitem>
	        <listitem>Katkıcılardan gelen uygulamaların kullanışlılık ve İBE kabul testleri yürütülecek, bu testler için süreç tanımı yapılacak ve kılavuz hazırlanacak.</listitem>
	      </numberedlist>
	      Proje iletişim: Serdar Köylü, <email>serdar@uludag.org.tr</email>
	    </para>
    </sect1>
  </chapter>

</book>

=== pars-linux/uludag/web/site/tr/projeler/sera/index.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE book SYSTEM "http://www.uludag.org.tr/style/uludagbook.dtd"
[
]>

<book version="0.1" lang="tr" type="webpage">

  <bookinfo>
    <title>Sera</title>

    <author author_id="1">
      <firstname>Zerrin</firstname>
      <lastname>Çakmakkaya</lastname>
      <address>
        <email>zerrin@uludag.org.tr</email>
      </address>
    </author>
    <author author_id="1">
      <firstname>Alp</firstname>
      <lastname>Öztarhan</lastname>
      <address>
	<email>alp@uludag.org.tr</email>
      </address>
    </author>

    <pubdate>2004-01-10</pubdate>
    <revhistory>
      <revision author_id="1">
        <revnumber>1.0</revnumber>
	<date>2004-01-10</date>
      </revision>
    </revhistory>

    <abstract>
      <para>
        Sera projesi, dağarcıktan sürüm oluşturmayı kolaylaştıran yazılımlar ve yöntemler üretmeyi hedefliyor. Sera projesinin girdisi Paketler, Paket Yönetim Sistemi ve Kurulum projelerinden elde edilecek. 
     </para>
   </abstract>
  </bookinfo>

  <chapter>
    <sect1>
      <para>
        Ulusal Dağıtım Sera Projesi kapsamında:
	<numberedlist>
	  <listitem> Paket yönetim sistemi, paket listesi ve kurulum programı parametrelerini alıp, dağarcıktan bir dağıtım CD'si imajı oluşturma işini yapan yazılımlar üretilecek</listitem>
	  <listitem> Kullanıcıya özel dağıtımların, istenilen paketler seçilerek kolayca oluşturulabilmesini sağlayacak yazılımlar üretilecek</listitem>
	</numberedlist>
      	
      Proje iletişim: Murat Eren, <email>meren@uludag.org.tr</email>
      </para>
    </sect1>
  </chapter>

</book>
