=== pars-linux/uludag/playground/intern/2009/yali-kahya/yalisema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="yali">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element name="language" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string ">
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="keymap" use="optional">
					<xs:simpleType>
						<xs:restriction base="xs:string">
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="root_password">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="4"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="hostname">
					<xs:simpleType>
						<xs:restriction base="xs:string"/>
					</xs:simpleType>
				</xs:element>
				<xs:element name="users">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded">
							<xs:element name="user">
								<xs:complexType>
									<xs:all>
										<xs:element name="username">
											<xs:simpleType>
												<xs:restriction base="xs:string"/>
											</xs:simpleType>
										</xs:element>
										<xs:element name="realname">
											<xs:simpleType>
												<xs:restriction base="xs:string"/>
											<xs:simpleType>
										</xs:element>
										<xs:element name="password">
											<xs:simpleType>
												<xs:restriction base="xs:string"/>
											</xs:simpleType>
										</xs:element>
										<xs:element name="groups">
											<xs:simpleType>
												<xs:restriction base="xs:string"/>
											</xs:simpleType>
										</xs:element>
										<xs:attribute name="autologin" use="optional" default="no"/>
									</xs:all>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:choice>
					<xs:element name="partioning">
						<xs:complexType>
							<xs:attribute name="partitioning_type" fixed="auto"/>
							<xs:element name="disk">
								<xs:simpleType>
									<xs:restriction base="xs:string"/>
								</xs:simpleType>
							</xs:element>
						</xs:complexType>
					</xs:element>		
					<xs:element name="partioning">
						<xs:complexType>
							<xs:attribute name="partitioning_type" fixed="manuel"/>
							<xs:element name="partition" use="required">
								<xs:complexType>
									<xs:attribute name="partition_type" type="xs:string" fixed="pardus_root"/>
									<xs:attribute name="format" default="true"/>
									<xs:attribute name="ratio" type="xs:int"/>
								</xs:complexType>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="/c{3}./d{1}"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="partition" use="optional">
								<xs:complexType>
									<xs:attribute name="partition_type" type="xs:string" fixed="pardus_swap"/>
									<xs:attribute name="format" default="true"/>
									<xs:attribute name="ratio" type="xs:int"/>
								</xs:complexType>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="/c{3}./d{1}"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="partition" use="optional">
								<xs:complexType>
									<xs:attribute name="partition_type" type="xs:string" fixed="pardus_home"/>
									<xs:attribute name="format" default="true"/>
									<xs:attribute name="ratio" type="xs:int"/>
								</xs:complexType>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="/c{3}./d{1}"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="partition" use="optional">
								<xs:complexType>
									<xs:attribute name="partition_type" type="xs:string" fixed="other"/>
									<xs:attribute name="format" default="true"/>
									<xs:attribute name="ratio" type="xs:int"/>
									<xs:attribute name="fs_type" type="xs:string"/>
									<xs:attribute name="mountpoint" type="xs:string"/>
								</xs:complexType>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="/c{3}./d{1}"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:complexType>
					</xs:element>
				</xs:choice>	
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== pars-linux/uludag/corporate/yali4/data/exampleKickstart.xml
<?xml version="1.0" encoding="iso-8859-9"?>
<yali xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="yalisema.xsd">
    <language>tr</language>
    <keymap>tr</keymap>
    <variant>q</variant>
    <root_password>pardusman</root_password>
    <hostname>pardus-kickstart</hostname>
    <!-- <users use_yali_first_boot="true"> -->
    <users>
        <user>
            <username>gokmen</username>
            <realname>gokmen goksel</realname>
            <password>1231111</password>
            <groups>audio,dialout,disk,pnp,pnpadmin,users,video,wheel</groups>
        </user>
        <user>
            <username>zeynep</username>
            <realname>zeynep sagar</realname>
            <password>123456</password>
            <groups>users,wheel,pnp</groups>
        </user>
        <!-- Wrong usage; root is unique user name 
        <user>
            <username>root</username>
            <realname>root user</realname>
            <password>123456</password>
            <groups>users,wheel,pnp</groups>
        </user>
        -->
    </users>
    <reponame>pardus-2007.3</reponame>
    <repoaddr>http://paketler.pardus.org.tr/pardus-remote-install/pisi-index.xml.bz2</repoaddr>
    <!--<partitioning partitioning_type="auto">disk0</partitioning>-->
    <partitioning partitioning_type="smartAuto">disk0</partitioning>
</yali>
